gestion_dechet1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('premierver.urls')),  # Inclure les URLs de l'application
    # Autres URLs globales...
]

premierver/urls.py
from django.urls import path
from .views import accueil, custom_login,liste_dechets, ajouter_dechet, details_dechet, modifier_dechet,index, supprimer_dechet
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [

    
    path('login', custom_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('', accueil, name='accueil'),
    path('',index, name='index'),

    path('dechets/', liste_dechets, name='liste_dechets'),
    path('dechets/ajouter/', ajouter_dechet, name='ajouter_dechet'),
    path('dechets/<int:dechet_id>/', details_dechet, name='details_dechet'),
    path('dechets/<int:dechet_id>/modifier/', modifier_dechet, name='modifier_dechet'),
    path('dechets/<int:dechet_id>/supprimer/', supprimer_dechet, name='supprimer_dechet'),
    # path('index', views.application, name='application'),  # La vue 'application' sera associée à la racine de votre site

]

premierver/models.py
from django.db import models

class Dechets(models.Model):
    Type_dechet = models.CharField(max_length=50)
    Description = models.TextField()
    Date_ajout = models.DateField()
    Etat = models.CharField(max_length=50)

class Points_de_collecte(models.Model):
    Nom_point_collecte = models.CharField(max_length=100)
    Adresse = models.TextField()
    Type_dechets_acceptes = models.CharField(max_length=100)
    Capacite_stockage = models.IntegerField()

class Collectes(models.Model):
    ID_point_collecte = models.ForeignKey(Points_de_collecte, on_delete=models.CASCADE)
    Date_collecte = models.DateField()
    Poids_total_collecte = models.DecimalField(max_digits=10, decimal_places=2)
    Type_dechets_collectes = models.CharField(max_length=100)

class Traitement(models.Model):
    ID_dechet = models.ForeignKey(Dechets, on_delete=models.CASCADE)
    Type_traitement = models.CharField(max_length=100)
    Date_traitement = models.DateField()
    Destination_traitement = models.CharField(max_length=100)

class Fournisseurs_de_services(models.Model):
    Nom_entreprise = models.CharField(max_length=100)
    Adresse = models.TextField()
    Type_service_offert = models.CharField(max_length=100)
    Contact = models.CharField(max_length=100)

premierver/forms.py
from django import forms
from .models import Dechets

class DechetForm(forms.ModelForm):
    class Meta:
        model = Dechets
        fields = ['Type_dechet', 'Description', 'Date_ajout', 'Etat']
class ImageUploadForm(forms.Form):
    image = forms.ImageField()

premierver/views.py
# views.py
from django.shortcuts import render
from django.contrib.auth import views as auth_views

def my_login_view(request):
    # Logique pour gérer la vue de connexion
    return auth_views.LoginView.as_view()(request)

def my_logout_view(request):
    # Logique pour gérer la vue de déconnexion
    return auth_views.LogoutView.as_view()(request)

def my_password_change_view(request):
    # Logique pour gérer la vue de changement de mot de passe
    return auth_views.PasswordChangeView.as_view()(request)

def my_password_change_done_view(request):
    # Logique pour gérer la vue de confirmation de changement de mot de passe
    return auth_views.PasswordChangeDoneView.as_view()(request)

def my_password_reset_view(request):
    # Logique pour gérer la vue de réinitialisation de mot de passe
    return auth_views.PasswordResetView.as_view()(request)

def my_password_reset_done_view(request):
    # Logique pour gérer la vue de confirmation d'envoi de lien de réinitialisation de mot de passe
    return auth_views.PasswordResetDoneView.as_view()(request)

def my_password_reset_confirm_view(request, uidb64, token):
    # Logique pour gérer la vue de confirmation de réinitialisation de mot de passe
    return auth_views.PasswordResetConfirmView.as_view()(request, uidb64=uidb64, token=token)

def my_password_reset_complete_view(request):
    # Logique pour gérer la vue de confirmation de réinitialisation de mot de passe complétée
    return auth_views.PasswordResetCompleteView.as_view()(request)

# views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm

def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Authentification réussie, redirigez l'utilisateur vers une page spécifique
            return redirect('accueil')  # Remplacez 'accueil' par le nom de l'URL de votre choix
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def accueil(request):
    return render(request, 'acceuil.html')
from django.shortcuts import render, redirect
from .models import Dechets

def liste_dechets(request):
    dechets = Dechets.objects.all()
    return render(request, 'liste_dechets.html', {'dechets': dechets})


from .forms import DechetForm

def ajouter_dechet(request):
    if request.method == 'POST':
        form = DechetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('liste_dechets')
    else:
        form = DechetForm()
    return render(request, 'ajouter_dechet.html', {'form': form})
from django.shortcuts import render
from .models import Dechets

def liste_dechets(request):
    dechets = Dechets.objects.all()
    return render(request, 'liste_dechets.html', {'dechets': dechets})


from django.shortcuts import render, redirect, get_object_or_404
from .forms import DechetForm
from .models import Dechets

def modifier_dechet(request, dechet_id):
    dechet = get_object_or_404(Dechets, pk=dechet_id)
    if request.method == 'POST':
        form = DechetForm(request.POST, instance=dechet)
        if form.is_valid():
            form.save()
            return redirect('details_dechet', dechet_id=dechet_id)
    else:
        form = DechetForm(instance=dechet)
    return render(request, 'modifier_dechet.html', {'form': form})

from django.shortcuts import redirect, get_object_or_404
from .models import Dechets

def supprimer_dechet(request, dechet_id):
    dechet = get_object_or_404(Dechets, pk=dechet_id)
    dechet.delete()
    return redirect('liste_dechets')


from django.shortcuts import render, get_object_or_404
from .models import Dechets

def details_dechet(request, dechet_id):
    dechet = get_object_or_404(Dechets, pk=dechet_id)
    return render(request, 'details_dechet.html', {'dechet': dechet})



# Import necessary Django modules
from django.shortcuts import render
from django.conf import settings
import os
# from .prediction import *

# Define your Django view function
def application(request):
    file = ""
    answer = None
    error = ""
    
    if request.method == "POST":
        try:
            file = request.FILES["image"]
            if file:
                # Save the uploaded file
                file_path = os.path.join(settings.MEDIA_ROOT, file.name)
                with open(file_path, 'wb+') as destination:
                    for chunk in file.chunks():
                        destination.write(chunk)
                
                # Get prediction
                result = predict(file.name)
                
                if result == "":
                    error = "Sorry!"
                else:
                    answer = result
                    
        except SyntaxError as e:
            error = "Could not understand"
            print("Error:" + str(e))

    return render(request, 'index.html', {'file': file,
                                          'answer': answer,
                                          'error': error})
# trash_classification/views.py
from django.shortcuts import render
from .forms import ImageUploadForm
import os
import cv2
import tensorflow as tf
import numpy as np
from keras.preprocessing import image
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

def predict(img_path):
    labels = {0: 'cardboard', 1: 'glass', 2: 'metal', 3: 'paper', 4: 'plastic'}
    img = image.load_img(img_path, target_size=(300, 300))
    img = image.img_to_array(img, dtype=np.uint8)
    img = np.array(img) / 255.0
     
    model = tf.keras.models.load_model("trained_model.h5")
    p = model.predict(img[np.newaxis, ...])
    pro = np.max(p[0], axis=-1)
    predicted_class = labels[np.argmax(p[0], axis=-1)]
    os.remove(img_path)
    return str(predicted_class) + " \n Probability:" + str(pro)

import os

def index(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image_file = form.cleaned_data['image']
            filename = image_file.name
            file_path = os.path.join('uploads', filename)
            
            # Créer le répertoire "uploads" s'il n'existe pas
            os.makedirs('uploads', exist_ok=True)
            
            with open(file_path, 'wb') as f:
                f.write(image_file.read())
            result = predict(file_path)
            return render(request, 'index.html', {'answer': result})
    else:
        form = ImageUploadForm()
    return render(request, 'index.html', {'form': form})

premierver/templates/acceuil.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
    <!-- Inclure Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Styles CSS personnalisés -->
    <style>
        body {
            background-color: #f8f9fa; /* Couleur de fond */
            color: #333; /* Couleur de texte principale */
        }
        .container {
            max-width: 800px; /* Largeur maximale du conteneur */
            margin: 0 auto; /* Centrer le contenu horizontalement */
            padding: 20px; /* Espacement interne du conteneur */
            margin-top: 50px; /* Espacement par rapport au haut de la page */
        }
        h1 {
            color: #007bff; /* Couleur du titre */
            margin-bottom: 20px; /* Espacement en dessous du titre */
        }
        .btn {
            margin-right: 10px; /* Marge à droite pour les boutons */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Bienvenue sur notre application de gestion des déchets</h1>
        <p>Cette application vous permet de gérer efficacement les déchets en ajoutant, modifiant et supprimant des informations sur les déchets.</p>
        <div>
            <a href="{% url 'liste_dechets' %}" class="btn btn-primary">Voir la liste des déchets</a>
            <!-- Ajoutez d'autres liens ou boutons selon les fonctionnalités de votre application -->
        </div>
        <div>    <p><a href="{% url 'logout' %}">Déconnexion</a></p>
        </div>
    </div>

    <!-- Inclure Bootstrap JS et jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

premierver/templates/ajouter_dechet.html
<!DOCTYPE html>
<html>
<head>
    <title>Ajouter un déchet</title>
    <!-- Inclure Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Styles CSS personnalisés -->
    <style>
        body {
            background-color: #f8f9fa; /* Couleur de fond */
            color: #333; /* Couleur de texte principale */
            padding-top: 50px; /* Espacement par rapport au haut de la page */
        }
        .container {
            max-width: 800px; /* Largeur maximale du conteneur */
            margin: 0 auto; /* Centrer le contenu horizontalement */
            padding: 0 15px; /* Espacement interne du conteneur */
        }
        h1 {
            color: #007bff; /* Couleur du titre */
            margin-bottom: 20px; /* Espacement en dessous du titre */
        }
        .form-group {
            margin-bottom: 20px; /* Espacement entre chaque groupe de champ */
        }
        label {
            font-weight: bold; /* Mettre en gras les labels des champs */
        }
        .form-control {
            width: 100%; /* Largeur des champs de formulaire */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Ajouter un déchet</h1>
        <form method="post">
            {% csrf_token %}
            <div class="card">
            <div class="form-group">
                <label for="id_Type_dechet">Type de déchet :</label>
                {{ form.Type_dechet }}
            </div>
            <div >
                <label for="id_Description" class="card-text">Description :</label>
                {{ form.Description }}
            </div>
            <div class="form-group">
                <label for="id_Date_ajout" class="card-text">Date d'ajout :</label>
                {{ form.Date_ajout }}
            </div>
            <div class="form-group">
                <label for="id_Etat"  class="card-text">État :</label>
                {{ form.Etat }}
            </div>
            <button type="submit" class="btn btn-primary">Ajouter</button>
        </form>
    </div>
</div>
    <!-- Inclure Bootstrap JS et jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

premierver/templates/details_dechet.html
<!DOCTYPE html>
<html>
<head>
    <title>Détails du déchet</title>
    <!-- Inclure Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Détails du déchet</h1>
        <div class="card">
            <div class="card-body">
                <p class="card-text"><strong>Type de déchet :</strong> {{ dechet.Type_dechet }}</p>
                <p class="card-text"><strong>Description :</strong> {{ dechet.Description }}</p>
                <p class="card-text"><strong>Date d'ajout :</strong> {{ dechet.Date_ajout }}</p>
                <p class="card-text"><strong>État :</strong> {{ dechet.Etat }}</p>
                <a href="{% url 'modifier_dechet' dechet.id %}" class="btn btn-primary">Modifier</a>
                <a href="{% url 'supprimer_dechet' dechet.id %}" class="btn btn-danger">Supprimer</a>
                <a href="{% url 'liste_dechets' %}" class="btn btn-secondary">Retour à la liste des déchets</a>
            </div>
        </div>
    </div>

    <!-- Inclure Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

premierver/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Trash Classification</title>
    <style>
        /* Styles CSS */
        h1 {
            color: blue;
        }

        form {
            margin-top: 20px;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        table, th, td {
            border: 1px solid black;
        }

        th, td {
            padding: 10px;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
<div class="page">
    <h1>Detection de type de dechets</h1>
    <br>
    <p>Enter your input image:</p>
    <form method="POST" id="form" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <label>
            <input type="file" accept="image/png, image/jpeg, image/gif" name="image"id="fileInput"/>
        </label>
        <input type="submit" value="Submit">
        
        {% if error %}
            <p class="error"><strong>Error:</strong> {{ error }} </p>
        {% endif %}
    </form>

    {% if answer is not none %}
        <p><label name='answer'>Classified: {{ answer }}</label><br /></p>
    {% endif %}

    <!-- Tableau des catégories -->
    <table>
        <tr>
            <th>Category</th>
        </tr>
        <tr>
            <td>cardboard</td>
        </tr>
        <tr>
            <td>glass</td>
        </tr>
        <tr>
            <td>metal</td>
        </tr>
        <tr>
            <td>paper</td>
        </tr>
        <tr>
            <td>plastic</td>
        </tr>
    </table>
</div>

<script>
    // JavaScript
    document.getElementById("form").addEventListener("submit", function(event) {
        var fileInput = document.getElementById("fileInput");
        if (!fileInput.value) {
            alert("Please select an image.");
            event.preventDefault();
        }
    });
</script>

</body>
</html>

premierver/templates/liste_dechets.html
<!DOCTYPE html>
<html>
<head>
    <title>Liste des déchets</title>
    <!-- Inclure Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Styles CSS personnalisés -->
    <style>
        body {
            background-color: #f8f9fa; /* Couleur de fond */
            color: #333; /* Couleur de texte principale */
            padding-top: 50px; /* Espacement par rapport au haut de la page */
        }
        .container {
            max-width: 800px; /* Largeur maximale du conteneur */
            margin: 0 auto; /* Centrer le contenu horizontalement */
            padding: 0 15px; /* Espacement interne du conteneur */
        }
        h1 {
            color: #007bff; /* Couleur du titre */
            margin-bottom: 20px; /* Espacement en dessous du titre */
        }
        ul {
            list-style-type: none; /* Supprimer les puces de la liste */
            padding: 0; /* Supprimer le padding de la liste */
        }
        li {
            margin-bottom: 10px; /* Espacement entre chaque élément de la liste */
        }
        a {
            color: #007bff; /* Couleur des liens */
            text-decoration: none; /* Supprimer la soulignement des liens */
        }
        a:hover {
            text-decoration: underline; /* Soulignement au survol des liens */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Liste des déchets</h1>
        <ul>
            {% for dechet in dechets %}
                <li><a class="btn btn-primary" href="{% url 'details_dechet' dechet.id %}">{{ dechet.Type_dechet }}</a></li>
            {% endfor %}
        </ul>
        <a href="{% url 'ajouter_dechet' %}" class="btn btn-primary">Ajouter un déchet</a>
    </div>

    <!-- Inclure Bootstrap JS et jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

premierver/templates/login.html
<!-- login.html -->
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connexion</title>
    <!-- Intégration de Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Intégration de votre propre fichier CSS -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Connexion</h1>
        <form method="post" class="mt-3">
            {% csrf_token %}
            <!-- Utilisation des classes Bootstrap pour styliser le formulaire -->
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password }}
            </div>
            <button type="submit" class="btn btn-primary">Se connecter</button>
        </form>
    </div>
    <!-- Intégration de Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Intégration de votre propre fichier JavaScript -->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

premierver/templates/modifier_dechet.html
<!DOCTYPE html>
<html>
<head>
    <title>Modifier un déchet</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <div class="container mt-5">
    <h1>Modifier un déchet</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
    </form></div>

 <!-- Inclure Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

premierver/templates/my_protected_view.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vue Protégée</title>
</head>
<body>
    <h1>Contenu Protégé</h1>
    <p>Bienvenue, {{ request.user.username }}!</p>
    <p>Vous êtes maintenant dans une zone protégée.</p>
    <p>Voici quelques informations spécifiques à votre compte :</p>
    <ul>
        <li><strong>Nom d'utilisateur:</strong> {{ request.user.username }}</li>
        <li><strong>Email:</strong> {{ request.user.email }}</li>
        <!-- Vous pouvez ajouter d'autres informations de profil utilisateur ici -->
    </ul>
    <p><a href="{% url 'logout' %}">Déconnexion</a></p>
</body>
</html>